//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

// This file should be auto generated by onnx2c.py,
// it's used as driver for testing ONNX.

#include <math.h>

#include "common/rtlib.h"

double Expected_data[] = {20, 10, 3, 0};
int    Expected_len    = 4;

//! @brief Generate input data for testing ONNX
TENSOR* Generate_input_data(size_t n, size_t c, size_t h, size_t w,
                            double* data) {
  return Alloc_tensor(n, c, h, w, data);
}

//! @brief Validate output vector without expect vector
bool Validate_output_data(double* result, double* expect, int len) {
  double error = 1e-3;
  for (int i = 0; i < len; i++) {
    if (fabs(result[i] - expect[i]) > error) {
      printf("index: %d, value: %f != %f\n", i, result[i], expect[i]);
      return false;
    }
  }
  return true;
}

// for mult_const.onnx
int main(int argc, char* argv[]) {
  Prepare_context();

  double  input1[]    = {20, 10, 3, 0};
  TENSOR* input_data1 = Generate_input_data(1, 1, 2, 2, input1);
  printf("input");
  Print_tensor(stdout, input_data1);
  Prepare_input(input_data1, "input");
  Free_tensor(input_data1);

  Run_main_graph();

  double* result = Handle_output("output");

  Finalize_context();

  bool res = Validate_output_data(result, Expected_data, Expected_len);
  free(result);
  // This case is to check rt validate, which is expected failed.
  if (res) {
    printf("NOT EXPECTED SUCESS!\n");
    return 1;
  } else {
    printf("EXPECTED FAILED!\n");
  }
  return 0;
}

// NOTE: This inc file here should be replaced by c file, which is auto
// generated by irb2c from FHE compiler
#include "eg_fhertlib_mul_const_rtv.inc"