//-*-c++-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

#ifndef NN_VECTOR_CF_SIMP_CTX_H
#define NN_VECTOR_CF_SIMP_CTX_H

#include "air/base/instrument_ctx.h"
#include "air/opt/dfg_builder.h"
#include "air/opt/dfg_container.h"
#include "air/opt/ssa_build.h"
#include "air/opt/ssa_container.h"
#include "nn/core/attr.h"
#include "nn/core/default_handler.h"
#include "nn/vector/config.h"
#include "nn/vector/default_handler.h"
#include "nn/vector/vector_ctx.h"
#include "nn/vector/vector_enum.h"
#include "nn/vector/vector_opcode.h"
#include "nn/vector/vector_utils.h"

namespace nn {

namespace vector {

#define SUCC_MAX 3

using namespace air::base;
using namespace air::driver;

using CF_WORKLIST = std::vector<NODE_ID>;
using CF_MAP =
    std::map<NODE_ID, NODE_ID>;  // constant folding source and target map

class CF_SIMP_CTX : public INSTRUMENT_CTX {
public:
  CF_SIMP_CTX(FUNC_SCOPE* func_scope, VECTOR_CTX& ctx,
              const DRIVER_CTX* driver_ctx, const VECTOR_CONFIG& cfg)
      : _func_scope(func_scope),
        _ctx(ctx),
        _driver_ctx(driver_ctx),
        _config(cfg),
        _ssa_cntr(&_func_scope->Container()),
        _dfg_cntr(&_ssa_cntr),
        _dfg(&_dfg_cntr) {}

  // declare access API for VECTOR_CTX
  DECLARE_VECTOR_CTX_ACCESS_API(_ctx)

  // declare access API for VECTOR_CONFIG
  DECLARE_VECTOR_CONFIG_ACCESS_API(_config)

  // declare trace API for detail tracing
  DECLARE_TRACE_DETAIL_API(_config, _driver_ctx)

  void Build_ssa() {
    air::opt::SSA_BUILDER ssa_builder(_func_scope, &_ssa_cntr, _driver_ctx);
    ssa_builder.Perform();
  }
  void Build_dfg() {
    air::opt::DFG_BUILDER<> dfg_builder(&_dfg, _func_scope, &_ssa_cntr, {});
    dfg_builder.Perform();
  }

  air::opt::SSA_CONTAINER* Ssa_cntr() { return &_ssa_cntr; }

  air::opt::DFG_CONTAINER* Dfg_cntr() { return &_dfg_cntr; }

  air::base::CONTAINER* Container() { return _ssa_cntr.Container(); }

  void Run() {}

  //! @brief judge whether this op is the boundary op of constant folding.
  //! Conv, gemm and strided_slice(whose input is generated by conv) are
  //! boundary ops till now. These ops partition the region of constant folding
  //! which can make later constant folding effecient.
  bool Is_cf_boundary_op(NODE_PTR node) {
    if ((node->Opcode() == OPCODE(nn::core::NN, nn::core::OPCODE::CONV)) ||
        (node->Opcode() == OPCODE(nn::core::NN, nn::core::OPCODE::GEMM))) {
      return true;
    }

    // if the input of strided_slice node is generated by conv, then this
    // strided_slice node is also a boundary op.
    if (node->Opcode() ==
        OPCODE(nn::core::NN, nn::core::OPCODE::STRIDED_SLICE)) {
      NODE_PTR ss_input_node = node->Child(0);
      if (ss_input_node->Opcode() ==
          OPCODE(nn::core::NN, nn::core::OPCODE::CONV)) {
        return true;
      } else if ((ss_input_node->Opcode() == air::core::LD) ||
                 (ss_input_node->Opcode() == air::core::LDP)) {
        air::opt::SSA_CONTAINER* ssa_cntr = this->Ssa_cntr();
        air::opt::SSA_VER_PTR ssa_ver = ssa_cntr->Node_ver(ss_input_node->Id());
        AIR_ASSERT_MSG(ssa_ver->Kind() == air::opt::VER_DEF_KIND::STMT,
                       "must define by stmt");

        CONTAINER* cntr            = ssa_cntr->Container();
        NODE_PTR ss_input_def_node = cntr->Stmt(ssa_ver->Def_stmt_id())->Node();
        if (ss_input_def_node->Child(0)->Opcode() ==
            OPCODE(nn::core::NN, nn::core::OPCODE::CONV)) {
          return true;
        }
      }
    }
    return false;
  }

  NODE_PTR Get_def_node(NODE_PTR node) {
    AIR_ASSERT(node->Opcode() == air::core::OPC_LD ||
               node->Opcode() == air::core::OPC_LDP)
    air::opt::SSA_CONTAINER* ssa_cntr = this->Ssa_cntr();
    air::opt::SSA_VER_PTR    ssa_ver  = ssa_cntr->Node_ver(node->Id());
    AIR_ASSERT_MSG(ssa_ver->Kind() == air::opt::VER_DEF_KIND::STMT,
                   "must define by stmt");

    CONTAINER* cntr     = ssa_cntr->Container();
    NODE_PTR   def_node = cntr->Stmt(ssa_ver->Def_stmt_id())->Node();
    return def_node;
  }

  //! @brief judge whether it is a const multiplication operation
  bool Is_mul_const_op(NODE_PTR node) {
    if (((node->Opcode() ==
          OPCODE(nn::vector::VECTOR, nn::vector::VECTOR_OPCODE::MUL)) ||
         (node->Opcode() == OPCODE(nn::core::NN, nn::core::MUL))) &&
        (node->Child(1)->Opcode() == air::core::OPC_LDC)) {
      return true;
    }
    return false;
  }

  //! @brief judge whether this is a contant folding target node
  //! target node currenly are conv, gemm and
  //! mul op which multiply variable with constant
  //! these ops are the folding destination.
  bool Is_cf_target(NODE_PTR node) {
    if ((node->Opcode() == OPCODE(nn::core::NN, nn::core::GEMM)) ||
        (node->Opcode() == OPCODE(nn::core::NN, nn::core::CONV)) ||
        (((node->Opcode() ==
           OPCODE(nn::vector::VECTOR, nn::vector::VECTOR_OPCODE::MUL)) ||
          (node->Opcode() == OPCODE(nn::core::NN, nn::core::MUL))) &&
         (node->Child(1)->Opcode() == air::core::OPC_LDC))) {
      return true;
    }
    return false;
  }

  //! @brief judge whether this is a contant folding target node
  //! target node currenly are conv, gemm and
  //! mul op which multiply variable with constant
  //! these ops are the folding destination.
  bool Is_cf_strong_target(NODE_PTR node) {
    if ((node->Opcode() == OPCODE(nn::core::NN, nn::core::GEMM)) ||
        (node->Opcode() == OPCODE(nn::core::NN, nn::core::CONV))) {
      return true;
    }
    return false;
  }

  //! @brief judge whether this is a contant folding target node
  //! target node currenly are conv, gemm and
  //! mul op which multiply variable with constant
  //! these ops are the folding destination.
  bool Is_cf_weak_target(NODE_PTR node) {
    if ((((node->Opcode() ==
           OPCODE(nn::vector::VECTOR, nn::vector::VECTOR_OPCODE::MUL)) ||
          (node->Opcode() == OPCODE(nn::core::NN, nn::core::MUL))) &&
         (node->Child(1)->Opcode() == air::core::OPC_LDC))) {
      return true;
    }
    return false;
  }

  template <typename T>
  T Get_scalar(NODE_PTR node) {
    AIR_ASSERT_MSG(node->Rtype()->Cast_to_arr()->Elem_count() == 1,
                   "multiply node's second child must only contain 1 value");
    T val = node->Const()->Array_elem<T>(0);
    return val;
  }

  void Register_cf_node(NODE_ID node) { _cf_wl.push_back(node); }

  SS_WORKLIST Get_cf_worklist() { return _cf_wl; }

  air::opt::DFG_NODE_PTR Get_dfg_node(NODE_ID node) {
    air::opt::DFG_CONTAINER* dfg_cntr = this->Dfg_cntr();
    air::opt::DFG_NODE_PTR   dfg_node = dfg_cntr->Node(dfg_cntr->Node_id(node));
    return dfg_node;
  }

  std::vector<NODE_ID> Find_cf_candidate(NODE_ID node_id) {
    NODE_PTR               debug_node = this->Container()->Node(node_id);
    air::opt::DFG_NODE_PTR dfg_node   = this->Get_dfg_node(node_id);
    // get def node
    air::opt::DFG_NODE_PTR dfg_def_node = dfg_node->Succ()->Dst();

    std::vector<NODE_ID> candidate;
    // traverse all successor(use site) and analyze whether there is constant
    // folding target, if yes, add to candidate.
    uint32_t succ_count = 0;
    for (auto iter = dfg_def_node->Begin_succ();
         iter != dfg_def_node->End_succ(); ++iter) {
      succ_count++;
      air::opt::DFG_EDGE_PTR edge      = *iter;
      air::opt::DFG_NODE_PTR dst_node  = edge->Dst();
      NODE_PTR               succ_node = dst_node->Node();

      // indicate this is the last node
      if (succ_node->Opcode() == air::core::RET ||
          succ_node->Opcode() == air::core::RETV) {
        AIR_ASSERT(succ_count == 1);
        // candidate.push_back(succ_node->Id());
        break;
      }

      if (Is_cf_strong_target(succ_node)) {
        candidate.push_back(succ_node->Id());
        break;
      } else if (Is_cf_weak_target(succ_node)) {
        candidate.push_back(succ_node->Id());
        // prop to next succ node
        std::vector<NODE_ID> sub_candidate = Find_cf_candidate(succ_node->Id());
        if (sub_candidate.size() > 0) {
          candidate.insert(std::end(candidate), std::begin(sub_candidate),
                           std::end(sub_candidate));
        }
      } else if (succ_node->Opcode() == OPCODE(nn::core::NN, nn::core::ADD)) {
        // a * x + conv(y), constant a should not propagate to laster op.
        // need to check add op's another child, currently is conv
        NODE_PTR opnd1 = Get_def_node(succ_node->Child(0));
        NODE_PTR opnd2 = Get_def_node(succ_node->Child(1));
        if (Is_cf_strong_target(opnd1->Child(0)) ||
            Is_cf_strong_target(opnd2->Child(0))) {
          continue;
        } else {
          // prop to next succ node
          std::vector<NODE_ID> sub_candidate =
              Find_cf_candidate(succ_node->Id());
          if (sub_candidate.size() > 0) {
            candidate.insert(std::end(candidate), std::begin(sub_candidate),
                             std::end(sub_candidate));
          }
        }
      } else {
        // prop to next succ node
        std::vector<NODE_ID> sub_candidate = Find_cf_candidate(succ_node->Id());
        if (sub_candidate.size() > 0) {
          candidate.insert(std::end(candidate), std::begin(sub_candidate),
                           std::end(sub_candidate));
        }
      }
    }

    // successor node should not exceed SUCC_MAX till now
    AIR_ASSERT(succ_count < SUCC_MAX);

    return candidate;
  }

  std::vector<NODE_ID> Find_cf_candidate_ngraph(NODE_ID node_id) {
    NODE_PTR               debug_node = this->Container()->Node(node_id);
    air::opt::DFG_NODE_PTR dfg_node   = this->Get_dfg_node(node_id);
    // get def node
    air::opt::DFG_NODE_PTR dfg_def_node = dfg_node->Succ()->Dst();

    std::vector<NODE_ID> candidate;

    // ngraph only give 3 patterns:
    // 1. avgpool-conv
    // 2. relu(ax^2+bx+c) - Conv/Gemm
    // 3. Conv/Gemm-BatchNorm(done by AI infrastructure)

    // traverse all successor(use site) and analyze whether there is constant
    // folding target, if yes, add to candidate.
    if (dfg_def_node->Succ_count() == 1) {
      air::opt::DFG_EDGE_PTR edge      = *(dfg_def_node->Begin_succ());
      air::opt::DFG_NODE_PTR dst_node  = edge->Dst();
      NODE_PTR               succ_node = dst_node->Node();

      // ngraph has no strided_slice, so pass to next successor
      if (succ_node->Opcode() ==
          OPCODE(nn::core::NN, nn::core::STRIDED_SLICE)) {
        // get def node
        air::opt::DFG_NODE_PTR later_dfg_def_node = dst_node->Succ()->Dst();
        air::opt::DFG_EDGE_PTR new_edge = *(later_dfg_def_node->Begin_succ());
        dst_node                        = new_edge->Dst();
        succ_node                       = dst_node->Node();
      }

      // indicate this is the last node
      if (succ_node->Opcode() == air::core::RET ||
          succ_node->Opcode() == air::core::RETV) {
        // candidate.push_back(succ_node->Id());
        return candidate;
      }

      if (Has_attr<int>(debug_node, core::ATTR::NGRAPH)) {
        if (succ_node->Opcode() == OPCODE(nn::core::NN, nn::core::CONV)) {
          candidate.push_back(succ_node->Id());
        }
      } else {
        if ((succ_node->Opcode() == OPCODE(nn::core::NN, nn::core::GEMM)) ||
            (succ_node->Opcode() == OPCODE(nn::core::NN, nn::core::CONV))) {
          candidate.push_back(succ_node->Id());
        }
      }
    }

    return candidate;
  }

  CF_MAP Cf_analyze() {
    CF_MAP      cf_map;
    CF_WORKLIST cf_worklist = this->Get_cf_worklist();
    for (const NODE_ID mulc_node_id : cf_worklist) {
      NODE_PTR debug_node = this->Container()->Node(mulc_node_id);
      // debug_node->Print();

      std::vector<NODE_ID> candidates;
      if (_config.Ngraph_cf()) {
        candidates = Find_cf_candidate_ngraph(mulc_node_id);
      } else {
        candidates = Find_cf_candidate(mulc_node_id);
      }

      // TODO: some has more than 1 target node, see case 9 and 10, 8.17
      NODE_ID cf_target = air::base::Null_id;
      if (candidates.size() > 0) {
        cf_target  = candidates[candidates.size() - 1];
        debug_node = this->Container()->Node(cf_target);
        //! the last candidates are the constant folding target node
        cf_map.insert(std::pair<NODE_ID, NODE_ID>(mulc_node_id, cf_target));
      }
    }
    return cf_map;
  }

private:
  FUNC_SCOPE*                  _func_scope;
  VECTOR_CTX&                  _ctx;
  const DRIVER_CTX*            _driver_ctx;
  const VECTOR_CONFIG&         _config;
  air::opt::SSA_CONTAINER      _ssa_cntr;
  air::opt::DFG_CONTAINER      _dfg_cntr;
  air::opt::DFG_CONTAINER::DFG _dfg;
  CF_WORKLIST                  _cf_wl;  // used for constant folding
};

class CF_SIMP_NN_HANDLER : public nn::core::DEFAULT_HANDLER {
public:
  template <typename RETV, typename VISITOR>
  RETV Handle_mul(VISITOR* visitor, air::base::NODE_PTR node) {
    CF_SIMP_CTX& ctx = visitor->Context();

    air::opt::DFG_NODE_PTR dfg_node = ctx.Get_dfg_node(node->Id());
    // get def node
    air::opt::DFG_NODE_PTR dfg_def_node = dfg_node->Succ()->Dst();

    bool     succ_contain_add = false;
    uint32_t succ_count       = 0;
    for (auto iter = dfg_def_node->Begin_succ();
         iter != dfg_def_node->End_succ(); ++iter) {
      air::opt::DFG_EDGE_PTR edge      = *iter;
      air::opt::DFG_NODE_PTR dst_node  = edge->Dst();
      NODE_PTR               succ_node = dst_node->Node();
      succ_count++;
      if (succ_node->Opcode() == OPCODE(nn::core::NN, nn::core::ADD)) {
        succ_contain_add = true;
      }
    }

    // TODO: this is pattern match.
    if (ctx.Is_mul_const_op(node)) {
      if (!(succ_contain_add && (succ_count == 1))) {
        ctx.Register_cf_node(node->Id());
      }
    }

    return RETV();
  }

};  // CF_SIMP_NN_HANDLER

class CF_SIMP_VECTOR_HANDLER : public nn::vector::DEFAULT_HANDLER {
public:
  template <typename RETV, typename VISITOR>
  RETV Handle_mul(VISITOR* visitor, air::base::NODE_PTR node) {
    CF_SIMP_CTX& ctx = visitor->Context();

    if (ctx.Is_mul_const_op(node)) {
      ctx.Register_cf_node(node->Id());
    }

    return RETV();
  }

};  // CF_SIMP_VECTOR_HANDLER

}  // namespace vector

}  // namespace nn

#endif  // NN_VECTOR_CF_SIMP_CTX_H
