//-*-c++-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

#ifndef NN_VECTOR_COPY_PROP_CTX_H
#define NN_VECTOR_COPY_PROP_CTX_H

#include "air/base/instrument_ctx.h"
#include "air/core/default_handler.h"
#include "air/opt/dfg_builder.h"
#include "air/opt/dfg_container.h"
#include "air/opt/ssa_build.h"
#include "air/opt/ssa_container.h"
#include "nn/core/default_handler.h"
#include "nn/vector/config.h"
#include "nn/vector/vector_ctx.h"
#include "nn/vector/vector_enum.h"
#include "nn/vector/vector_opcode.h"
#include "nn/vector/vector_utils.h"

namespace nn {

namespace vector {

using namespace air::base;
using namespace air::driver;

class COPY_PROP_CTX : public INSTRUMENT_CTX {
public:
  COPY_PROP_CTX(FUNC_SCOPE* func_scope, VECTOR_CTX& ctx,
                const DRIVER_CTX* driver_ctx, const VECTOR_CONFIG& cfg)
      : _func_scope(func_scope),
        _ctx(ctx),
        _driver_ctx(driver_ctx),
        _config(cfg),
        _ssa_cntr(&_func_scope->Container()),
        _dfg_cntr(&_ssa_cntr),
        _dfg(&_dfg_cntr) {}

  // declare access API for VECTOR_CTX
  DECLARE_VECTOR_CTX_ACCESS_API(_ctx)

  // declare access API for VECTOR_CONFIG
  DECLARE_VECTOR_CONFIG_ACCESS_API(_config)

  // declare trace API for detail tracing
  DECLARE_TRACE_DETAIL_API(_config, _driver_ctx)

  void Build_ssa() {
    air::opt::SSA_BUILDER ssa_builder(_func_scope, &_ssa_cntr, _driver_ctx);
    ssa_builder.Perform();
  }
  void Build_dfg() {
    air::opt::DFG_BUILDER<> dfg_builder(&_dfg, _func_scope, &_ssa_cntr, {});
    dfg_builder.Perform();
  }

  air::opt::SSA_CONTAINER* Ssa_cntr() { return &_ssa_cntr; }

  air::base::CONTAINER* Container() { return _ssa_cntr.Container(); }

  void Run() {}

  //! @brief judge whether this op is the boundary op of constant folding.
  //! Conv, gemm and strided_slice(whose input is generated by conv) are
  //! boundary ops till now. These ops partition the region of constant folding
  //! which can make later constant folding effecient.
  bool Is_cf_boundary_op(NODE_PTR node) {
    if ((node->Opcode() == OPCODE(nn::core::NN, nn::core::OPCODE::CONV)) ||
        (node->Opcode() == OPCODE(nn::core::NN, nn::core::OPCODE::GEMM))) {
      return true;
    }

    // if the input of strided_slice node is generated by conv, then this
    // strided_slice node is also a boundary op.
    if (node->Opcode() ==
        OPCODE(nn::core::NN, nn::core::OPCODE::STRIDED_SLICE)) {
      NODE_PTR ss_input_node = node->Child(0);
      if (ss_input_node->Opcode() ==
          OPCODE(nn::core::NN, nn::core::OPCODE::CONV)) {
        return true;
      } else if ((ss_input_node->Opcode() == air::core::LD) ||
                 (ss_input_node->Opcode() == air::core::LDP)) {
        air::opt::SSA_CONTAINER* ssa_cntr = this->Ssa_cntr();
        air::opt::SSA_VER_PTR ssa_ver = ssa_cntr->Node_ver(ss_input_node->Id());
        AIR_ASSERT_MSG(ssa_ver->Kind() == air::opt::VER_DEF_KIND::STMT,
                       "must define by stmt");

        CONTAINER* cntr            = ssa_cntr->Container();
        NODE_PTR ss_input_def_node = cntr->Stmt(ssa_ver->Def_stmt_id())->Node();
        if (ss_input_def_node->Child(0)->Opcode() ==
            OPCODE(nn::core::NN, nn::core::OPCODE::CONV)) {
          return true;
        }
      }
    }
    return false;
  }

  STMT_PTR Get_def_stmt(NODE_PTR node) {
    AIR_ASSERT(node->Opcode() == air::core::OPC_LD ||
               node->Opcode() == air::core::OPC_LDP)
    air::opt::SSA_CONTAINER* ssa_cntr = this->Ssa_cntr();
    air::opt::SSA_VER_PTR    ssa_ver  = ssa_cntr->Node_ver(node->Id());
    AIR_ASSERT_MSG(ssa_ver->Kind() == air::opt::VER_DEF_KIND::STMT,
                   "must define by stmt");

    CONTAINER* cntr     = ssa_cntr->Container();
    STMT_PTR   def_stmt = cntr->Stmt(ssa_ver->Def_stmt_id());
    return def_stmt;
  }

  NODE_PTR Get_def_node(NODE_PTR node) {
    AIR_ASSERT(node->Opcode() == air::core::OPC_LD ||
               node->Opcode() == air::core::OPC_LDP)
    air::opt::SSA_CONTAINER* ssa_cntr = this->Ssa_cntr();
    air::opt::SSA_VER_PTR    ssa_ver  = ssa_cntr->Node_ver(node->Id());
    AIR_ASSERT_MSG(ssa_ver->Kind() == air::opt::VER_DEF_KIND::STMT,
                   "must define by stmt");

    CONTAINER* cntr     = ssa_cntr->Container();
    NODE_PTR   def_node = cntr->Stmt(ssa_ver->Def_stmt_id())->Node();
    return def_node;
  }

  //! @brief judge whether it is a const multiplication operation
  bool Is_mul_const_op(NODE_PTR node) {
    if (((node->Opcode() ==
          OPCODE(nn::vector::VECTOR, nn::vector::VECTOR_OPCODE::MUL)) ||
         (node->Opcode() == OPCODE(nn::core::NN, nn::core::MUL))) &&
        (node->Child(1)->Opcode() == air::core::OPC_LDC)) {
      return true;
    }
    return false;
  }

  //! @brief judge whether it is a const multiplication operation
  bool Is_ss_op(NODE_PTR node) {
    if (node->Opcode() == OPCODE(nn::core::NN, nn::core::STRIDED_SLICE)) {
      return true;
    }
    return false;
  }

  template <typename T>
  T Get_scalar(NODE_PTR node) {
    AIR_ASSERT_MSG(node->Rtype()->Cast_to_arr()->Elem_count() == 1,
                   "multiply node's second child must only contain 1 value");
    T val = node->Const()->Array_elem<T>(0);
    return val;
  }

  bool Is_pool_ax2_relu_pattern(NODE_PTR node) {
    NODE_PTR child_def1 = this->Get_def_node(node->Child(0));
    NODE_PTR child_node = child_def1->Child(0);  // x mul x node
    if (child_node->Opcode() == OPCODE(nn::core::NN, nn::core::MUL)) {
      NODE_PTR grandson_opnd1 =
          this->Get_def_node(child_node->Child(0))->Child(0);
      NODE_PTR grandson_opnd2 =
          this->Get_def_node(child_node->Child(1))->Child(0);
      if ((grandson_opnd1->Id() == grandson_opnd2->Id()) &&
          (grandson_opnd1->Opcode() == OPCODE(nn::core::NN, nn::core::MUL))) {
        return true;
      }
    }
    return false;
  }

  STMT_PTR Get_hard_code_def_stmt(NODE_PTR node) {
    NODE_PTR child_def1     = this->Get_def_node(node->Child(0));
    NODE_PTR child_node     = child_def1->Child(0);  // x mul x node
    STMT_PTR grandson_opnd1 = this->Get_def_stmt(child_node->Child(0));
    return grandson_opnd1;
  }

  float Hard_code_get_value(NODE_PTR node) {
    float result  = 1;
    float mul_val = node->Child(1)->Const()->Float_literal().Val_as_float();
    result        = mul_val;
    return result;
  }

  PREG_PTR Save_temp_preg(NODE_PTR node) {
    CONTAINER* cntr     = this->Container();
    PREG_PTR   new_preg = cntr->Parent_func_scope()->New_preg(node->Rtype());
    STMT_PTR   st_preg  = cntr->New_stp(node, new_preg, node->Spos());
    this->Prepend(st_preg);
    return new_preg;
  }

private:
  FUNC_SCOPE*                  _func_scope;
  VECTOR_CTX&                  _ctx;
  const DRIVER_CTX*            _driver_ctx;
  const VECTOR_CONFIG&         _config;
  air::opt::SSA_CONTAINER      _ssa_cntr;
  air::opt::DFG_CONTAINER      _dfg_cntr;
  air::opt::DFG_CONTAINER::DFG _dfg;
};

class NORMALIZE_HANDLER : public nn::core::DEFAULT_HANDLER {
public:
  template <typename RETV, typename VISITOR>
  RETV Handle_add(VISITOR* visitor, air::base::NODE_PTR node) {
    COPY_PROP_CTX& ctx    = visitor->Context();
    CONTAINER*     cntr   = ctx.Container();
    GLOB_SCOPE*    gscope = cntr->Glob_scope();

    NODE_PTR opnd1 = node->Child(0);
    NODE_PTR opnd2 = node->Child(1);

    NODE_PTR def1 = ctx.Get_def_node(opnd1);
    NODE_PTR def2 = ctx.Get_def_node(opnd2);

    NODE_PTR op1 = def1->Child(0);
    NODE_PTR op2 = def2->Child(0);

    // transform x^2*a + x*b to a*(x^2 + x*(b/a))
    if (ctx.Is_mul_const_op(op1) && ctx.Is_mul_const_op(op2)) {
      // for small cases which input starts with ax^2 relu
      bool from_begining = false;
      if (op2->Child(0)->Has_sym()) {
        air::base::ADDR_DATUM_PTR var = op2->Child(0)->Addr_datum();
        if (var->Is_formal()) {
          from_begining = true;
        }
      }
      if (!from_begining && ctx.Is_pool_ax2_relu_pattern(op1)) {
        STMT_PTR hc_pattern_stmt =
            ctx.Get_hard_code_def_stmt(op1);  // concat def stmt
        NODE_PTR hc_pattern_op = hc_pattern_stmt->Node()->Child(0);
        float    first_val     = ctx.Hard_code_get_value(hc_pattern_op);

        // get left const value
        NODE_PTR l_mul_const = op1->Child(1);
        float    l_mul_val   = ctx.Get_scalar<float>(l_mul_const);

        // get right const value
        NODE_PTR r_mul_const = op2->Child(1);
        float    r_mul_val   = ctx.Get_scalar<float>(r_mul_const);

        TYPE_PTR elem_type = node->Rtype()->Cast_to_arr()->Elem_type();

        // Floating point division may cause loss of precision.
        CONSTANT_PTR new_r_mul_val =
            gscope->New_const(CONSTANT_KIND::FLOAT, elem_type,
                              (long double)r_mul_val / l_mul_val / first_val);
        NODE_PTR new_r_mul_node = cntr->New_ldc(new_r_mul_val, node->Spos());

        // get x' * (b/ac)
        NODE_PTR new_r_node = cntr->New_bin_arith(
            OPCODE(nn::core::NN, nn::core::OPCODE::MUL), node->Rtype(),
            hc_pattern_op->Child(0), new_r_mul_node, node->Spos());

        // save new mul result to preg
        PREG_PTR mul_preg = ctx.Save_temp_preg(new_r_node);

        // change x*x to new x' * x'
        NODE_PTR mul_x_x = ctx.Get_def_node(op1->Child(0))->Child(0);
        mul_x_x->Set_child(0, hc_pattern_op->Child(0));
        mul_x_x->Set_child(1, hc_pattern_op->Child(0));

        // get x'^2 + x'*(b/ac)
        node->Set_child(0, op1->Child(0));
        node->Set_child(1, cntr->New_ldp(mul_preg, node->Spos()));

        // save add result to preg
        PREG_PTR add_preg = ctx.Save_temp_preg(node);

        // get const a*c*c
        CONSTANT_PTR new_l_mul_const =
            gscope->New_const(CONSTANT_KIND::FLOAT, elem_type,
                              (long double)l_mul_val * first_val * first_val);
        NODE_PTR new_l_mul_node = cntr->New_ldc(new_l_mul_const, node->Spos());

        // get new node: a*c*c* (x'^2 + x'*(b/ac))
        NODE_PTR result_node = cntr->New_bin_arith(
            OPCODE(nn::core::NN, nn::core::OPCODE::MUL), node->Rtype(),
            cntr->New_ldp(add_preg, node->Spos()), new_l_mul_node,
            node->Spos());

        // get the parent node of current node.
        NODE_PTR parent_node = ctx.Parent(1);
        // change appropriate child to new node
        for (uint32_t i = 0; i < parent_node->Num_child(); i++) {
          if (parent_node->Child(i)->Id() == node->Id()) {
            parent_node->Set_child(i, result_node);
          }
        }

        // delete useless def site
        STMT_LIST stmt_list = STMT_LIST::Enclosing_list(def1->Stmt());
        stmt_list.Remove(def1->Stmt());
        stmt_list.Remove(def2->Stmt());
        stmt_list.Remove(hc_pattern_stmt);
      } else {
        // get left const value
        NODE_PTR l_mul_const = op1->Child(1);
        float    l_mul_val   = ctx.Get_scalar<float>(l_mul_const);

        // get right const value
        NODE_PTR r_mul_const = op2->Child(1);
        float    r_mul_val   = ctx.Get_scalar<float>(r_mul_const);

        TYPE_PTR elem_type = node->Rtype()->Cast_to_arr()->Elem_type();

        // Floating point division may cause loss of precision.
        CONSTANT_PTR new_r_mul_val =
            gscope->New_const(CONSTANT_KIND::FLOAT, elem_type,
                              (long double)r_mul_val / l_mul_val);
        NODE_PTR new_r_mul_node = cntr->New_ldc(new_r_mul_val, node->Spos());

        // get x * (b/a)
        NODE_PTR new_r_node = cntr->New_bin_arith(
            OPCODE(nn::core::NN, nn::core::OPCODE::MUL), node->Rtype(),
            op2->Child(0), new_r_mul_node, node->Spos());

        // save new mul result to preg
        PREG_PTR mul_preg = ctx.Save_temp_preg(new_r_node);

        // get x^2 + x*(b/a)
        node->Set_child(0, op1->Child(0));
        node->Set_child(1, cntr->New_ldp(mul_preg, node->Spos()));

        // save add result to preg
        PREG_PTR add_preg = ctx.Save_temp_preg(node);

        // get const a
        CONSTANT_PTR new_l_mul_const = gscope->New_const(
            CONSTANT_KIND::FLOAT, elem_type, (long double)l_mul_val);
        NODE_PTR new_l_mul_node = cntr->New_ldc(new_l_mul_const, node->Spos());

        // get new node: a* (x^2 + x*(b/a))
        NODE_PTR result_node = cntr->New_bin_arith(
            OPCODE(nn::core::NN, nn::core::OPCODE::MUL), node->Rtype(),
            cntr->New_ldp(add_preg, node->Spos()), new_l_mul_node,
            node->Spos());

        // get the parent node of current node.
        NODE_PTR parent_node = ctx.Parent(1);
        // change appropriate child to new node
        for (uint32_t i = 0; i < parent_node->Num_child(); i++) {
          if (parent_node->Child(i)->Id() == node->Id()) {
            parent_node->Set_child(i, result_node);
          }
        }

        // delete useless def site
        STMT_LIST stmt_list = STMT_LIST::Enclosing_list(def1->Stmt());
        stmt_list.Remove(def1->Stmt());
        stmt_list.Remove(def2->Stmt());
      }
    }

    return RETV();
  }

  template <typename RETV, typename VISITOR>
  RETV Handle_concat(VISITOR* visitor, air::base::NODE_PTR node) {
    COPY_PROP_CTX& ctx    = visitor->Context();
    CONTAINER*     cntr   = ctx.Container();
    GLOB_SCOPE*    gscope = cntr->Glob_scope();

    NODE_PTR opnd1 = node->Child(0);
    NODE_PTR opnd2 = node->Child(1);

    NODE_PTR def1 = ctx.Get_def_node(opnd1);
    NODE_PTR def2 = ctx.Get_def_node(opnd2);

    NODE_PTR op1 = def1->Child(0);
    NODE_PTR op2 = def2->Child(0);

    // transform concat(ss(a*roll_sum(x)), ss(a*roll_sum(y))) to
    // a*(concat(ss(roll_sum(x)), ss(roll_sum(y))))
    if (ctx.Is_ss_op(op1) && ctx.Is_ss_op(op2)) {
      NODE_PTR grandson_def1 = ctx.Get_def_node(op1->Child(0));
      NODE_PTR grandson_def2 = ctx.Get_def_node(op2->Child(0));

      NODE_PTR gradson_op1 = grandson_def1->Child(0);
      NODE_PTR gradson_op2 = grandson_def2->Child(0);

      if (ctx.Is_mul_const_op(gradson_op1) &&
          ctx.Is_mul_const_op(gradson_op2)) {
        // get left const value
        NODE_PTR l_mul_const = gradson_op1->Child(1);
        float l_mul_val = l_mul_const->Const()->Float_literal().Val_as_float();

        // get right const value
        NODE_PTR r_mul_const = gradson_op2->Child(1);
        float r_mul_val = r_mul_const->Const()->Float_literal().Val_as_float();

        AIR_ASSERT(l_mul_val - r_mul_val < 0.01);

        // remove the mul * constant from their defination
        grandson_def1->Set_child(0, gradson_op1->Child(0));
        grandson_def2->Set_child(0, gradson_op2->Child(0));

        // save concat result to preg
        PREG_PTR concat_preg = ctx.Save_temp_preg(node);

        // get const a
        TYPE_PTR     elem_type = node->Rtype()->Cast_to_arr()->Elem_type();
        CONSTANT_PTR new_l_mul_const = gscope->New_const(
            CONSTANT_KIND::FLOAT, elem_type, (long double)l_mul_val);
        NODE_PTR new_l_mul_node = cntr->New_ldc(new_l_mul_const, node->Spos());

        // get new node: a*(concat(,,))
        NODE_PTR result_node = cntr->New_bin_arith(
            OPCODE(nn::core::NN, nn::core::OPCODE::MUL), node->Rtype(),
            cntr->New_ldp(concat_preg, node->Spos()), new_l_mul_node,
            node->Spos());

        // get the parent node of current node.
        NODE_PTR parent_node = ctx.Parent(1);
        // change appropriate child to new node
        for (uint32_t i = 0; i < parent_node->Num_child(); i++) {
          if (parent_node->Child(i)->Id() == node->Id()) {
            parent_node->Set_child(i, result_node);
          }
        }
      }
    }

    return RETV();
  }

};  // NORMALIZE_HANDLER

class NORMALIZE_VECTOR_HANDLER : public nn::vector::DEFAULT_HANDLER {
public:
  template <typename RETV, typename VISITOR>
  RETV Handle_mul(VISITOR* visitor, air::base::NODE_PTR node) {
    COPY_PROP_CTX& ctx  = visitor->Context();
    CONTAINER*     cntr = ctx.Container();

    if (ctx.Is_mul_const_op(node)) {
      if (node->Child(0)->Opcode() ==
          OPCODE(nn::vector::VECTOR, nn::vector::VECTOR_OPCODE::ROLL_SUM)) {
        // save roll_sum result to preg
        PREG_PTR rs_preg = ctx.Save_temp_preg(node->Child(0));
        node->Set_child(0, cntr->New_ldp(rs_preg, node->Spos()));
      }
    }

    return RETV();
  }

};  // CF_SIMP_VECTOR_HANDLER

}  // namespace vector

}  // namespace nn

#endif  // NN_VECTOR_COPY_PROP_CTX_H
