//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

// This file should be auto generated by onnx2c.py,
// it's used as driver for testing ONNX.

#include <math.h>

#include "common/rtlib.h"

double Expected_data[] = {0.08668368, 0.00488766, 1.1930607, 0.20228984};
int    Expected_len    = 4;

//! @brief Generate input data for testing ONNX
//! @param data data pointer
//! @return TENSOR input data
TENSOR* Generate_input_data(size_t n, size_t c, size_t h, size_t w,
                            double* data) {
  return Alloc_tensor(n, c, h, w, data);
}

/**
 * @brief validate output vector with expect vector
 *
 *
 * @param result double *
 * @param expect double *
 * @param len int
 * @return return true if value match
 */
bool Validate_output_data_absolute_error(double *result, double *expect, int len) {
  bool print_all = false;
  const char* print_all_str = getenv("PRINT_ALL");
  if(print_all_str != NULL) {
    printf("Value of PRINT_ALL: %s\n", print_all_str);
    print_all = true;
  }

  const char* absolute_error_str = getenv("ABS_ERROR");
  double absolute_error = 0.0001;
  if(absolute_error_str != NULL) {
    printf("Value of ABS_ERROR: %s\n", absolute_error_str);
    absolute_error = atof(absolute_error_str);
  }
  printf("expect absolute error less than: %f\n", absolute_error);
  int count = 0;
  for(int i = 0; i < len; i++) {
    double result_absolute_error = fabs(result[i] - expect[i]);
    if(print_all) {
      printf("index: %d, result: %f, expect: %f, result absolute error=%f, ", i, result[i], expect[i], result_absolute_error);
      if(result_absolute_error > absolute_error) {
        count++;
        printf("%d failed\n", count);
      } else {
        printf("ok\n");
      }
    } else {
      if(result_absolute_error > absolute_error) {
        printf("index: %d, value: %f != %f, result absolute error=%f\n", i, result[i], expect[i], result_absolute_error);
        return false;
      }
    }
  }
  if(print_all && (count != 0)) {
    return false;
  }
  return true;
}

bool Validate_output_data_relative_error(double *result, double *expect, int len) {
  bool print_all = false;
  const char* print_all_str = getenv("PRINT_ALL");
  if(print_all_str != NULL) {
    printf("Value of PRINT_ALL: %s\n", print_all_str);
    print_all = true;
  }

  const char* relative_error_str = getenv("REL_ERROR");
  double relative_error = 0.001;
  if(relative_error_str != NULL) {
    printf("Value of REL_ERROR: %s\n", relative_error_str);
    relative_error = atof(relative_error_str);
  }
  printf("expect relative error less than: %f\n", relative_error);
  int count = 0;
  for(int i = 0; i < len; i++) {
    double result_relative_error = fabs(result[i] - expect[i])/expect[i];
    if(print_all) {
      printf("index: %d, result: %f, expect: %f, result relative error=%f, ", i, result[i], expect[i], result_relative_error);
      if(result_relative_error > relative_error) {
        count++;
        printf("%d failed\n", count);
      } else {
        printf("ok\n");
      }
    } else {
      if (result_relative_error > relative_error) {
        printf("index: %d, value: %f != %f, result relative error: %f\n", i, result[i], expect[i], result_relative_error);
        return false;
      }
    }
  }
  if(print_all && (count != 0)) {
    return false;
  }
  return true;
}

// for mult_const.onnx
int main(int argc, char* argv[]) {
  Prepare_context();

  double  input1[]    = {0.29442092776298523, -0.06991183012723923,
                         -1.092273235321045, -0.4497664272785187};
  TENSOR* input_data1 = Generate_input_data(1, 1, 2, 2, input1);
  printf("input");
  Print_tensor(stdout, input_data1);
  Prepare_input(input_data1, "input");
  Free_tensor(input_data1);

  Run_main_graph();

  double* result = Handle_output("output");

  Finalize_context();

  bool    res_relative    = Validate_output_data_relative_error(result, Expected_data, Expected_len);
  bool    res_absolute    = Validate_output_data_absolute_error(result, Expected_data, Expected_len);
  free(result);
  if (res_relative || res_absolute) {
    printf("SUCCESS!\n");
  } else {
    printf("FAILED!\n");
    return 1;
  }
  return 0;
}

// NOTE: This inc file here should be replaced by c file, which is auto
// generated by irb2c from FHE compiler
#include "eg_fhertlib_relin.inc"