//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

// This file should be auto generated by onnx2c.py,
// it's used as driver for testing ONNX.

#include <math.h>

#include "common/rtlib.h"

double Expected_data[] = {0.037699066, 0.055039324, 0.037252523, 0.0, 0.0, 0.0,
                          0.08852681,  0.061008103, 0.025452413};
int    Expected_len    = 9;

/**
 * @brief generate input data for testing ONNX
 *
 *
 * @param n
 * @param c
 * @param h
 * @param w
 * @param data, data pointer
 * @return TENSOR input data
 */
TENSOR* Generate_input_data(size_t n, size_t c, size_t h, size_t w,
                            double* data) {
  return Alloc_tensor(n, c, h, w, data);
}

/**
 * @brief validate output vector with expect vector
 *
 *
 * @param result double *
 * @param expect double *
 * @param len int
 * @return return true if value match
 */
bool Validate_output_data_absolute_error(double* result, double* expect,
                                         int len) {
  bool        print_all     = false;
  const char* print_all_str = getenv("PRINT_ALL");
  if (print_all_str != NULL) {
    printf("Value of PRINT_ALL: %s\n", print_all_str);
    print_all = true;
  }

  const char* absolute_error_str = getenv("ABS_ERROR");
  double      absolute_error     = 0.0001;
  if (absolute_error_str != NULL) {
    printf("Value of ABS_ERROR: %s\n", absolute_error_str);
    absolute_error = atof(absolute_error_str);
  }
  printf("expect absolute error less than: %f\n", absolute_error);
  int count = 0;
  for (int i = 0; i < len; i++) {
    double result_absolute_error = fabs(result[i] - expect[i]);
    if (print_all) {
      printf("index: %d, result: %f, expect: %f, result absolute error=%f, ", i,
             result[i], expect[i], result_absolute_error);
      if (result_absolute_error > absolute_error) {
        count++;
        printf("%d failed\n", count);
      } else {
        printf("ok\n");
      }
    } else {
      if (result_absolute_error > absolute_error) {
        printf("index: %d, value: %f != %f, result absolute error=%f\n", i,
               result[i], expect[i], result_absolute_error);
        return false;
      }
    }
  }
  if (print_all && (count != 0)) {
    return false;
  }
  return true;
}

bool Validate_output_data_relative_error(double* result, double* expect,
                                         int len) {
  bool        print_all     = false;
  const char* print_all_str = getenv("PRINT_ALL");
  if (print_all_str != NULL) {
    printf("Value of PRINT_ALL: %s\n", print_all_str);
    print_all = true;
  }

  const char* relative_error_str = getenv("REL_ERROR");
  double      relative_error     = 0.001;
  if (relative_error_str != NULL) {
    printf("Value of REL_ERROR: %s\n", relative_error_str);
    relative_error = atof(relative_error_str);
  }
  printf("expect relative error less than: %f\n", relative_error);
  int count = 0;
  for (int i = 0; i < len; i++) {
    double result_relative_error = fabs(result[i] - expect[i]) / expect[i];
    if (print_all) {
      printf("index: %d, result: %f, expect: %f, result relative error=%f, ", i,
             result[i], expect[i], result_relative_error);
      if (result_relative_error > relative_error) {
        count++;
        printf("%d failed\n", count);
      } else {
        printf("ok\n");
      }
    } else {
      if (result_relative_error > relative_error) {
        printf("index: %d, value: %f != %f, result relative error: %f\n", i,
               result[i], expect[i], result_relative_error);
        return false;
      }
    }
  }
  if (print_all && (count != 0)) {
    return false;
  }
  return true;
}

int main(int argc, char* argv[]) {
  Prepare_context();

  double input1[] = {
      0.03769906610250473,  0.05503932386636734,   0.0372525230050087,
      -0.09148931503295898, -0.019985534250736237, -0.07158853113651276,
      0.08852680772542953,  0.06100810319185257,   0.02545241266489029};
  TENSOR* input_data1 = Generate_input_data(1, 1, 3, 3, input1);
  printf("input");
  Print_tensor(stdout, input_data1);
  Prepare_input(input_data1, "input");
  Free_tensor(input_data1);

  Run_main_graph();

  double* result = Handle_output("output");

  Finalize_context();

  bool res_relative =
      Validate_output_data_relative_error(result, Expected_data, Expected_len);
  bool res_absolute =
      Validate_output_data_absolute_error(result, Expected_data, Expected_len);
  free(result);
  if (res_relative || res_absolute) {
    printf("SUCCESS!\n");
  } else {
    printf("FAILED!\n");
    return 1;
  }

  return 0;
}

#include "eg_rtseal_relu.inc"
