#!/usr/bin/env python3
#
# Copyright (c) Ant Group Co., Ltd
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

import argparse
import os
import shlex
import shutil
import subprocess
import sys
import tempfile

import ace_compile


RESNET_CIFAR10_MODELS = [
    "resnet20_cifar10",
    "resnet32_cifar10",
    "resnet44_cifar10",
    "resnet56_cifar10",
    "resnet110_cifar10",
]

MODEL_ALIASES = {
    "20": "resnet20_cifar10",
    "32": "resnet32_cifar10",
    "44": "resnet44_cifar10",
    "56": "resnet56_cifar10",
    "110": "resnet110_cifar10",
    "resnet20": "resnet20_cifar10",
    "resnet32": "resnet32_cifar10",
    "resnet44": "resnet44_cifar10",
    "resnet56": "resnet56_cifar10",
    "resnet110": "resnet110_cifar10",
}

DEFAULT_MAIN_INC = os.path.join(
    "fhe-cmplr", "rtlib", "phantom", "example", "resnet_cifar.main.inc"
)
DEFAULT_LINK_DIR = os.path.join("fhe-cmplr", "rtlib", "cheddar", "example")
DEFAULT_CIFAR10 = "cifar-10-batches-bin"
DEFAULT_ROT_KEY_MODE = "pow2"
DEFAULT_ENCODE_MODE = "ondemand"
DEFAULT_PRE_ENCODE_COUNT = 64


def normalize_model_name(model):
    normalized = MODEL_ALIASES.get(model, model)
    if normalized not in RESNET_CIFAR10_MODELS:
        raise ValueError(
            "Unsupported model '{}'. Available models: {}".format(
                model, ", ".join(RESNET_CIFAR10_MODELS)
            )
        )
    return normalized


def normalize_models(models):
    if not models:
        return list(RESNET_CIFAR10_MODELS)

    normalized = []
    seen = set()
    for model in models:
        resolved = normalize_model_name(model)
        if resolved in seen:
            continue
        seen.add(resolved)
        normalized.append(resolved)
    return normalized


def resolve_cifar10_input(cifar10_arg, repo_root):
    resolved = ace_compile.resolve_path(cifar10_arg, repo_root)
    if os.path.isfile(resolved):
        return resolved

    if os.path.isdir(resolved):
        candidate = os.path.join(resolved, "test_batch.bin")
        if os.path.isfile(candidate):
            return candidate
        raise FileNotFoundError(
            "CIFAR-10 directory does not contain test_batch.bin: {}".format(resolved)
        )

    raise FileNotFoundError(
        "CIFAR-10 input not found: {}. Pass a test_batch.bin file or its parent directory.".format(
            resolved
        )
    )


def build_driver_source(model, main_inc):
    main_inc = os.path.abspath(main_inc)
    return """//-*-c-*-
//=============================================================================
//
// Auto-generated by scripts/ace_resnet_cifar10_infer.py.
// It reuses the shared CIFAR-10 runtime main from the Phantom example.
//
//=============================================================================

#define CIFAR_CLASS_COUNT 10
#include "{main_inc}"
#include "{model}_gpu.onnx.inc"
""".format(main_inc=main_inc, model=model)


def create_driver_file(model, main_inc):
    temp_dir = tempfile.mkdtemp(prefix=f"{model}_gpu_")
    driver_path = os.path.join(temp_dir, f"{model}_gpu.cu")
    with open(driver_path, "w") as handle:
        handle.write(build_driver_source(model, main_inc))
    return driver_path


def build_target(build_script, build_dir, driver_file, output_file, model):
    env = os.environ.copy()
    if build_dir:
        env["ACE_BUILD_DIR"] = build_dir

    command = [build_script, driver_file, output_file]
    return ace_compile.run_command(command, f"Build target {model}", env=env)


def find_example_executable(build_dir, model):
    exe_name = f"{model}_gpu"
    candidates = [
        os.path.join(build_dir, "example", exe_name),
        os.path.join(build_dir, "rtlib", "build", "example", exe_name),
    ]
    for candidate in candidates:
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate

    for root, _, files in os.walk(build_dir):
        if exe_name not in files:
            continue
        if "example" not in root.split(os.sep):
            continue
        candidate = os.path.join(root, exe_name)
        if os.access(candidate, os.X_OK):
            return candidate

    raise FileNotFoundError(
        "Built executable not found for {} under {}".format(model, build_dir)
    )


def apply_runtime_env_overrides(env, args):
    env.setdefault("RTLIB_BTS_EVEN_POLY", "1")
    env.setdefault("RT_BTS_CLEAR_IMAG", "1")
    env["CHEDDAR_ROT_KEY_MODE"] = args.rot_key_mode

    if args.encode_mode == "pre":
        pre_encode_count = (
            DEFAULT_PRE_ENCODE_COUNT
            if args.pre_encode_count is None
            else args.pre_encode_count
        )
        env["PT_PRE_ENCODE_COUNT"] = str(pre_encode_count)
    else:
        env.pop("PT_PRE_ENCODE_COUNT", None)

    if args.omp_threads is not None:
        env["OMP_NUM_THREADS"] = str(args.omp_threads)

    return env


def run_inference(executable, cifar10_bin, index, num, args):
    if num <= 0:
        raise ValueError("--num must be greater than 0")

    end = index + num - 1
    command = [executable, cifar10_bin, str(index), str(end)]
    env = apply_runtime_env_overrides(os.environ.copy(), args)

    timed_command = ace_compile.build_timed_command(command)
    print("Run command: {}".format(shlex.join(timed_command)))
    ret = subprocess.run(timed_command, env=env)
    if ret.returncode == 0:
        print("Run {} : SUCCESS!".format(os.path.basename(executable)))
    else:
        print("Run {} : FAILED!".format(os.path.basename(executable)))
    return ret


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Compile cheddar ResNet20/32/44/56/110 targets and run real CIFAR-10 "
            "inference with the shared Phantom CIFAR runtime main."
        )
    )
    parser.add_argument(
        "--root",
        default=ace_compile.get_default_repo_root(),
        help="ACE repository root. Defaults to ACE_ROOT or the directory of this script.",
    )
    parser.add_argument(
        "--compiler",
        help="Path to fhe_cmplr. Relative paths are resolved from --root.",
    )
    parser.add_argument(
        "--model-dir",
        help="Directory containing ONNX models. Relative paths are resolved from --root.",
    )
    parser.add_argument(
        "--link-dir",
        help=(
            "Directory for generated *.onnx.inc files. "
            "Building cheddar targets requires the default cheddar example directory."
        ),
    )
    parser.add_argument(
        "--build-script",
        help="Path to scripts/build_target_gpu.sh. Relative paths are resolved from --root.",
    )
    parser.add_argument(
        "--build-dir",
        help="Build directory passed to scripts/build_target_gpu.sh through ACE_BUILD_DIR.",
    )
    parser.add_argument(
        "--main-inc",
        default=DEFAULT_MAIN_INC,
        help=(
            "Path to the shared CIFAR runtime main inc file. Default: "
            f"{DEFAULT_MAIN_INC}"
        ),
    )
    parser.add_argument(
        "--model",
        action="append",
        dest="models",
        help=(
            "Model to run. Supports resnet20/resnet32/resnet44/resnet56/resnet110 "
            "or the full *_cifar10 names. Can be passed multiple times."
        ),
    )
    parser.add_argument(
        "--input-name",
        help="Override the ONNX input filename for all selected models.",
    )
    parser.add_argument(
        "--vec",
        default=ace_compile.DEFAULT_VEC_OPTION,
        help=f"Vectorization option passed to fhe_cmplr. Default: {ace_compile.DEFAULT_VEC_OPTION}",
    )
    parser.add_argument(
        "--sihe",
        action="append",
        dest="sihe_options",
        default=[],
        help=(
            "Additional SIHE option. Can be passed multiple times. Accepts either "
            "`foo:bar` or `-SIHE:foo:bar`. Model-specific ReLU SIHE options are "
            "appended automatically."
        ),
    )
    parser.add_argument(
        "--bwr",
        action="store_true",
        help="Append `bwr` to the SIHE options for every selected model.",
    )
    parser.add_argument(
        "--ckks",
        default=ace_compile.DEFAULT_CKKS_OPTION,
        help=f"CKKS option passed to fhe_cmplr. Default: {ace_compile.DEFAULT_CKKS_OPTION}",
    )
    parser.add_argument(
        "--icl",
        type=int,
        help=(
            "Set `icl=<val>` in the CKKS options to control the input ciphertext level. "
            "Overrides any existing `icl=` already present in `--ckks`."
        ),
    )
    parser.add_argument(
        "--sbm",
        action="store_true",
        help="Append `sbm` to the CKKS options for every selected model.",
    )
    parser.add_argument(
        "--sm",
        action="store_true",
        help="Append `sm` to the CKKS options for every selected model.",
    )
    parser.add_argument(
        "--p2c",
        default=ace_compile.DEFAULT_P2C_OPTION,
        help=f"P2C option passed to fhe_cmplr. Default: {ace_compile.DEFAULT_P2C_OPTION}",
    )
    parser.add_argument(
        "--df",
        default=ace_compile.DEFAULT_DF_TEMPLATE,
        help=(
            "Set or override `df=...` in the P2C option for every selected model. "
            f"Supports `{{model}}` in the path. Default: {ace_compile.DEFAULT_DF_TEMPLATE}"
        ),
    )
    parser.add_argument(
        "--compiler-option",
        action="append",
        dest="compiler_options",
        default=[],
        help="Extra compiler option appended after vec/sihe/ckks/p2c. Can be passed multiple times.",
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="Keep compiler-generated intermediate .t and .json files.",
    )
    parser.add_argument(
        "--skip-compile",
        action="store_true",
        help="Skip ONNX compilation and reuse existing generated *.onnx.inc files.",
    )
    parser.add_argument(
        "--skip-link",
        action="store_true",
        help="Skip building the cheddar executable and reuse an existing one.",
    )
    parser.add_argument(
        "--skip-run",
        action="store_true",
        help="Only compile/build, skip the final CIFAR-10 inference execution.",
    )
    parser.add_argument(
        "--fusion",
        action="store_true",
        help=(
            "Append `-CKKS:fus` during compilation. It is accepted for CLI compatibility, "
            "but the fusion pass is only effective on the Phantom backend."
        ),
    )
    parser.add_argument(
        "--cifar10",
        default=DEFAULT_CIFAR10,
        help="Path to test_batch.bin, or the directory that contains it.",
    )
    parser.add_argument(
        "-i",
        "--index",
        type=int,
        default=0,
        help="Index of the starting CIFAR-10 image.",
    )
    parser.add_argument(
        "-n",
        "--num",
        type=int,
        default=1,
        help="Number of CIFAR-10 images to run for each model.",
    )
    parser.add_argument(
        "--omp-threads",
        type=int,
        help="Override OMP_NUM_THREADS when running inference.",
    )
    parser.add_argument(
        "--rot-key-mode",
        choices=("pow2", "full"),
        default=DEFAULT_ROT_KEY_MODE,
        help=(
            "CHEDDAR rotation key strategy for runtime key preparation. "
            f"Default: {DEFAULT_ROT_KEY_MODE}"
        ),
    )
    parser.add_argument(
        "--encode-mode",
        choices=("ondemand", "pre"),
        default=DEFAULT_ENCODE_MODE,
        help=(
            "Plaintext encoding mode for CHEDDAR runtime. "
            "`ondemand` leaves data unencoded until used; `pre` triggers runtime "
            f"pre-encoding. Default: {DEFAULT_ENCODE_MODE}"
        ),
    )
    parser.add_argument(
        "--pre-encode-count",
        type=int,
        help=(
            "Maximum number of rt-data entries to pre-encode when "
            "`--encode-mode pre` is used. Set 0 for uncapped best effort. "
            f"Default when pre-encode is enabled: {DEFAULT_PRE_ENCODE_COUNT}"
        ),
    )
    parser.add_argument(
        "--keep-driver",
        action="store_true",
        help="Keep the generated temporary *_gpu.cu wrapper in the cheddar example directory.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if args.sbm and args.sm:
        raise ValueError("`--sbm` and `--sm` cannot be enabled at the same time.")
    if args.num <= 0:
        raise ValueError("`--num` must be greater than 0.")
    if args.pre_encode_count is not None and args.pre_encode_count < 0:
        raise ValueError("`--pre-encode-count` must be >= 0.")
    repo_root = ace_compile.resolve_path(args.root)
    compiler = ace_compile.resolve_path(
        args.compiler or ace_compile.get_default_compiler(repo_root), repo_root
    )
    model_dir = ace_compile.resolve_path(args.model_dir or "model", repo_root)
    link_dir = ace_compile.resolve_path(args.link_dir or DEFAULT_LINK_DIR, repo_root)
    build_script = ace_compile.resolve_path(
        args.build_script or os.path.join("scripts", "build_target_gpu.sh"), repo_root
    )
    build_dir = ace_compile.resolve_path(args.build_dir or "release", repo_root)
    main_inc = ace_compile.resolve_path(args.main_inc, repo_root)
    default_link_dir = ace_compile.resolve_path(DEFAULT_LINK_DIR, repo_root)

    if not os.path.isfile(main_inc):
        raise FileNotFoundError(f"Main inc file not found: {main_inc}")

    if not args.skip_link and os.path.normpath(link_dir) != os.path.normpath(default_link_dir):
        raise ValueError(
            "Building cheddar executables requires --link-dir to be {} "
            "because scripts/build_target_gpu.sh copies the wrapper there.".format(
                default_link_dir
            )
        )

    args.backend = "cheddar"
    models = normalize_models(args.models)

    cifar10_bin = None
    if not args.skip_run:
        cifar10_bin = resolve_cifar10_input(args.cifar10, repo_root)

    print(f"ACE root: {repo_root}")
    print(f"Compiler: {compiler}")
    print("Backend: cheddar")
    print(f"Model dir: {model_dir}")
    print(f"Link dir: {link_dir}")
    print(f"Build script: {build_script}")
    print(f"Build dir: {build_dir}")
    print(f"Main inc: {main_inc}")
    print(f"Models: {', '.join(models)}")
    print(f"Compiler vec option: {args.vec}")
    print(f"Compiler ckks option: {args.ckks}")
    if args.icl is not None:
        print(f"Compiler icl: {args.icl}")
    print(f"Compiler p2c option: {args.p2c}")
    if args.df:
        print(f"Compiler df template: {args.df}")
    if args.sbm:
        print("Compiler sbm: enabled")
    if args.sm:
        print("Compiler sm: enabled")
    if args.bwr:
        print("Compiler bwr: enabled")
    if args.fusion:
        print("Compiler fusion: requested")
    if args.sihe_options:
        print(f"User SIHE options: {args.sihe_options}")
    if args.compiler_options:
        print(f"Extra compiler options: {args.compiler_options}")
    if cifar10_bin is not None:
        print(f"CIFAR-10 file: {cifar10_bin}")
        print(f"Infer images: [{args.index}, {args.index + args.num - 1}]")
    print(f"Rotation key mode: {args.rot_key_mode}")
    print(f"Encode mode: {args.encode_mode}")
    if args.encode_mode == "pre":
        pre_encode_count = (
            DEFAULT_PRE_ENCODE_COUNT
            if args.pre_encode_count is None
            else args.pre_encode_count
        )
        print(f"Pre-encode count: {pre_encode_count}")
    if args.omp_threads is not None:
        print(f"OMP threads override: {args.omp_threads}")

    exit_code = 0

    for model in models:
        print()
        print("=" * 80)
        print(f"Processing {model}")
        print("=" * 80)

        input_file = os.path.join(
            model_dir, ace_compile.get_model_input_filename(model, model_dir, args)
        )
        output_file = os.path.join(link_dir, f"{model}_gpu.onnx.inc")
        generated_driver = None
        copied_driver = os.path.join(link_dir, f"{model}_gpu.cu")
        copied_driver_existed = os.path.exists(copied_driver)

        try:
            if not args.skip_compile:
                compile_options = ace_compile.build_compile_options(model, args, repo_root)
                print(
                    f"Resolved compile options for {model}: "
                    f"{shlex.join(compile_options)}"
                )
                compile_ret = ace_compile.compile_model(
                    compiler,
                    model,
                    input_file,
                    output_file,
                    compile_options,
                    keep=args.keep,
                )
                if compile_ret.returncode != 0:
                    exit_code = compile_ret.returncode
                    continue
            elif not os.path.isfile(output_file):
                raise FileNotFoundError(
                    f"Generated include file not found for {model}: {output_file}"
                )

            if not args.skip_link:
                generated_driver = create_driver_file(model, main_inc)
                build_ret = build_target(
                    build_script,
                    build_dir,
                    generated_driver,
                    output_file,
                    model,
                )
                if build_ret.returncode != 0:
                    exit_code = build_ret.returncode
                    continue

            executable = None
            if not args.skip_link or not args.skip_run:
                executable = find_example_executable(build_dir, model)
                print(f"Executable: {executable}")

            if not args.skip_run:
                run_ret = run_inference(
                    executable,
                    cifar10_bin,
                    args.index,
                    args.num,
                    args,
                )
                if run_ret.returncode != 0:
                    exit_code = run_ret.returncode
        except (FileNotFoundError, ValueError) as err:
            print(err, file=sys.stderr)
            exit_code = 1
        finally:
            if generated_driver:
                shutil.rmtree(os.path.dirname(generated_driver), ignore_errors=True)
            if (
                not args.keep_driver
                and not copied_driver_existed
                and os.path.exists(copied_driver)
            ):
                os.remove(copied_driver)

    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
