version: "2.0"

# Code Style Check

parameters:
  image_build:  "reg.docker.alibaba-inc.com/avh/avh:regex"

  # aarch64
  image_aarch64_build: "reg.docker.alibaba-inc.com/avh/avh:regex_aarch64"

stages:
  - check

jobs:
  code.style:
    stage: check
    id: regex
    component: ant-code-build
    inputs:
      name: build-air-infra
      resourceClass: XL
      environment:
        type: LINUX_CONTAINER
        image: ${{parameters.image_build}}
      buildTasks:
        - name: Install Dependency
          commands: |
            echo "Install ..."
        - name: Build
          commands: |
            cmake -S code-repo -B build -GNinja
            cmake --build build -- -j8
      timeout: 7200

  code.style_aarch64:
    stage: check
    id: regex_aarch64
    component: ant-code-build
    inputs:
      name: build-air-infra
      resourceClass: XL
      environment:
        type: LINUX_CONTAINER_ARM64
        image: ${{parameters.image_aarch64_build}}
      buildTasks:
        - name: Install Dependency
          commands: |
            echo "Install ..."
        - name: Build
          commands: |
            cmake -S code-repo -B build -GNinja
            cmake --build build -- -j8
      timeout: 7200